cjolowicz/cookiecutter-hypermodern-python-instance

- CONTRIBUTING.md
GFM extensions, such as tables, emojis, and checkboxes, are not formatted correctly in Sphinx documentation. Markdown input for Sphinx is processed by `recommonmark`, an implementation of the CommonMark standard, which does not handle proprietary extensions such as GFM.
> Avoid GFM extensions in Contributor Guide

- noxfile.py
> Support Python 3.9 in Nox sessions

- .github/workflows/coverage.yml
- noxfile.py
There is no longer any need for the coverage session, now that we upload to Codecov using their GitHub Action. Generate an XML coverage report from the tests session instead, passing `--cov-report=xml`.
> Remove coverage session

- mypy.ini
- noxfile.py
- src/cookiecutter_hypermodern_python_instance/__init__.py
Enable the strictness options associated with the `--strict` flag.
Also enable options for enhanced output (`--show-error-codes`, `--show-error-context`, `--show-column-numbers`, `--pretty`). 
Fix some issues in the code base due to the increased strictness:
- Use `sys.version_info` instead of `try...except ImportError`
- Ignore missing imports for `importlib_metadata`.
- Allow untyped decorators in Nox sessions and test suite.
- Fix `[no-any-return]` in `Poetry.version`.
> Configure mypy to be strict and pretty

- .pre-commit-config.yaml
- mypy.ini
This adds support for running mypy via pre-commit.
Like flake8 and black, mypy is run via Poetry using a [local hook]. This has the drawback that you need to run `poetry install` before you can use pre-commit with your project. On other hand, it allows you to manage these tools as development dependencies in Poetry. The alternative would be to have duplicate and potentially diverging version pins in the Poetry lock file and the pre-commit configuration. Also, pinning subdependencies does not appear to be very practical with pre-commit.
[local hook]: https://pre-commit.com/#repository-local-hooks
Set [mypy_path] in the configuration file pointing it to the `src` directory. This is required to avoid errors about missing imports related to your package when mypy is invoked on files located …
> Add pre-commit hook for mypy

- mypy.ini
- noxfile.py
Distribute inline type information using the `py.typed` marker file ([PEP 561]).
[pep 561]: https://www.python.org/dev/peps/pep-0561/
This allows us to remove `mypy_path` from mypy.ini.
Install the package into the Nox session for mypy. This is required to allow type-checking the test suite (when not also type-checking the package itself).
> Add py.typed marker file (PEP 561)

- .github/workflows/coverage.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
- .github/workflows/test-pypi.yml
- .github/workflows/tests.yml
There is no need to specify `architecture: x64` when using actions/setup-python.
x64 is the default architecture.
> Omit redundant architecture key for setup-python action

- noxfile.py
Poetry.export uses tempfile.NamedTemporaryFile to create a temporary
requirements file, passing the name of the temporary file to `poetry export` via
its `--output` option.
Unfortunately, this does not work on Windows. On Windows NT and later, the name
attribute of the file-like object returned by tempfile.NamedTemporaryFile cannot
be used to open the file a second time, while the named temporary file is still
open.
https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile
Instead, use tempfile.TemporaryDirectory to create a temporary directory, and
store a file named `requirements.txt` in that directory. This technique should
be both secure and portable.
> Fix tempfile usage in Poetry.export on Windows

- .github/workflows/pre-commit.yml
- Redesign cache key
- Allow partial matches (restore keys)
Key components:
- runner.os
- python version
- python executable
- pre-commit config
> Refactor pre-commit workflow

- .pre-commit-config.yaml
- noxfile.py
- poetry.lock
- pyproject.toml
- tests/test_main.py
This PR adds reorder-python-imports as a pre-commit hook. Like other Python hooks, it is added to the Poetry development dependencies and run as a repository-local hook.
For compatibility with reorder-python-imports, the minimum Python version of the template is raised from 3.6.0 to 3.6.1.
> Sort imports with reorder-python-imports

- .gitignore
Editor plugins may invoke mypy in subdirectories, leaving the cache directory all over the place.
> Ignore .mypy_cache/ in subdirectories

- .github/workflows/tests.yml
Just some minor changes to keep consistency:
- Added missing quotes for python versions
- Changed setup from Python 3.9 to 3.10
- Changed description of setup removing python version, as in release workflow.
> Update test GA workflow for more consistent style

- .readthedocs.yml
- 👷 [readthedocs] Switch to `build`-based YAML format
- 👷 [readthedocs] Use Python 3.10 on Read the Docs
> 👷 [readthedocs] Use Python 3.10 on Read the Docs

- .github/workflows/tests.yml
This has the positive side effect that Prettier won't wrap lines in the workflow matrix. There's no need to disambiguate here, e.g. between Python version and Python implementation, so the shorter name makes the workflow more readable, too.
> 👷 [github] Shorten `python-version` to `python` in Tests workflow matrix

- .github/workflows/tests.yml
- noxfile.py
Enable color output on GitHub Actions for the following tools:
| Tool         | Method                    |
|--------------|---------------------------|
| pre-commit   | `PRE_COMMIT_COLOR=always` |
| pytest       | `FORCE_COLOR=1`           |
| sphinx-build | `--color`                 |
| xdoctest     | `--colored=1`             |
- The command-line options for `sphinx-build` and `xdoctest` are passed by their respective Nox sessions when `FORCE_COLOR` is present in the environment.
- Do not enable colors for mypy (`MYPY_FORCE_COLOR`) because this environment variable does not actually have an effect on GitHub Actions, see https://github.com/python/mypy/issues/7771#issuecomment-876508529.
- Do not enable colors for flake8 (`--color=always`) because we cannot pass this option via …
> 👷 [github] Enable colors from pre-commit, pytest, Sphinx, and xdoctest

- pyproject.toml
Include the test suite in code coverage, via the [coverage.run.source] setting.
Rationale:
- Tests are code.
- Identify tests that aren’t running.
- Ensure that test helpers are used and tested.
Caveats:
- Coverage may require extra configuration if tests are deliberately excluded.
- Tests may clutter the coverage report. Use `--skip-covered` if this is an issue.
- The coverage metric generally goes up.
See https://nedbatchelder.com/blog/202008/you_should_include_your_tests_in_coverage.html
This PR also updates the [coverage.paths] setting, to map paths for the test suite to the local source tree. By default, coverage data contains absolute paths for the test suite. During CI, coverage data from various runners is combined in an environment where these paths do not exist. This results in …
> Include test suite in code coverage

- noxfile.py
Combine coverage data under the latest Python version supported by the measured
code. Combining data from Python 3.10 under Python 3.9 produces false positives
in branch coverage, where arcs leaving loop blocks are reported as missing.
Previously, the coverage session used the same Python interpreter as Nox. This
worked fine in CI, but could trigger the problem in local development, if Nox
was installed under an older interpreter such as Python 3.9.
> 👷 [nox] Combine coverage under the latest Python release

- noxfile.py
pre-commit 2.16.0 switched from Python to bash in the hooks installed to `.git/hooks`. We're patching hook scripts to activate the virtualenv for the `pre-commit` Nox session. This PR teaches the Nox session to detect bash hooks. The inserted fragment for virtualenv activation was ported to bash.
This PR also fixes a potential crash when files in the hook directory cannot be opened using the default text encoding. We're now checking that the binary file contents start with the shebang sequence `#!` before attempting to decode the contents. That should at least deal with binaries. Scripts with random garbage will still cause the hook installation to crash.
- 🔨 Split conditional
- 🔨 Replace `if not continue` with `if`
- ✨ Add bash version
- 🔨 Add comments with pre-commit version ranges
- 🔨 …
> ✨ [nox] Support patching pre-commit hooks written in bash

- noxfile.py
The patched pre-commit hooks installed by the `pre-commit` Nox session modify the `PATH` environment variable, using `os.pathsep` to separate prepended paths. On Git Bash for Windows, the path separator (`;`) is a shell-special character and needs to be quoted. This commit fixes the Nox session to quote the path separator when patching installed hooks.
This fixes the following error on Windows when invoking pre-commit hooks from Git:
```
.git/hooks/pre-commit: line 3: C:\Users\User\hypermodern-python\.nox\pre-commit\Scripts: Is a directory
.git/hooks/pre-commit: line 13: dirname: command not found
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
```
This issue does not affect pre-commit when run via Nox and in CI.
> 🐛 [nox] Fix patching of pre-commit hooks on Git Bash for Windows

- README.rst
- docs/index.rst
- When you remove `github-only` RST session and put full paths to RTD it simply works everywhere.
I tried in my own repo, you can check out: https://pypi.org/project/git-portfolio/
Closes https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/1091
> Fix broken contributing link on PyPI

- CODE_OF_CONDUCT.rst
- README.rst
Closes https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/1095
> Fix permanently moved links on Readme and Code of Conduct

- .github/dependabot.yml
Dependabot updates version constraints in pyproject.toml even when the version constraint already covers the new version, leading to frequent merge conflicts because the global content hash in poetry.lock changes. See https://github.com/dependabot/dependabot-core/issues/4435 for details.
As of cjolowicz/cookiecutter-hypermodern-python-instance#744, this project template no longer uses upper version bounds for its dependencies. As a result, we are now able to use the "lockfile-only" versioning strategy to upgrade dependencies, including major version bumps. This strategy prevents Dependabot from modifying pyproject.toml, putting an end to the frequent merge conflicts.
> 🔧 [dependabot] Reduce merge conflicts using the lockfile-only strategy

- .github/dependabot.yml
Configure Dependabot to keep both direct and indirect dependencies updated.
While the default setting of upgrading only direct dependencies means less churn, it also results in checks being run with increasingly outdated dependencies -- unless users are mindful of performing frequent manual updates. But typically they won't be because this project template *appears* to be automating all dependency updates. Often these outdated dependencies are only discovered when they get flagged by safety or Dependabot alerts due to security vulnerabilities.
> 🔧 [dependabot] Enable automated updates for indirect dependencies

- poetry.lock
- pyproject.toml
We must use the environment marker `python_version < 4` due to a Python version
cap declared by mdit-py-plugins, one of myst-parser's dependencies.
Closes https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/1132
> ➕ [poetry] Add myst-parser to development dependencies

- .pre-commit-config.yaml
- noxfile.py
Moves darglint to its own manual-stage pre-commit hook.
With this change, darglint will no longer run by default on every commit. But will run when the nox pre-commit session is called.
```console
% nox --session=pre-commit
```
Allowing us to still lint arguments in docstrings on demand and in the project's CI, while avoiding dealing with long wait times on each commit. 
Fixes https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/1137
> Move darglint to its own manual pre-commit hook

- poetry.lock
- pyproject.toml
- Restore upper bound on Requires-Python
- Remove python_version environment marker on myst-parser
Fixes https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/1148
Fixes https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/1154
Supercedes https://github.com/cjolowicz/cookiecutter-hypermodern-python/pull/1151
Supercedes https://github.com/cjolowicz/cookiecutter-hypermodern-python/pull/1152
> Restore upper bound to Python version constraint

- pyproject.toml
This setting has become the default behavior in mypy 0.991.
> Remove redundant `show_error_codes` setting for mypy

- .flake8
- .pre-commit-config.yaml
- bandit.yml
- noxfile.py
- poetry.lock
- pyproject.toml
See #970 
Closes https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/1244
This is #970 with an updated lock file. (New PR because I couldn't push to the original branch.)
> Replace flake8-bandit with bandit
