.github/workflows/coverage.yml
.github/workflows/release.yml
.github/workflows/test-pypi.yml
.github/workflows/tests.yml

This is a temporary workaround for https://github.com/pypa/virtualenv/issues/1589 (fixed in master).

Use virtualenv 16.7.9

---

.github/workflows/tests.yml

Support Python 3.9 on GitHub Actions, using [deadsnakes](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa).

Support Python 3.9

---

poetry.lock

Upgrade darglint from 1.1.3 to 1.2.0.

Upgrade to darglint 1.2.0

---

poetry.lock

Upgrade packaging from 20.1 to 20.3.

Upgrade to packaging 20.3

---

poetry.lock

Upgrade pygments from 2.5.2 to 2.6.1.

Upgrade to pygments 2.6.1

---

docs/requirements.txt
poetry.lock

Upgrade sphinx from 2.4.3 to 2.4.4.

Upgrade to sphinx 2.4.4

---

poetry.lock

Upgrade sphinxcontrib-applehelp from 1.0.1 to 1.0.2.

Upgrade to sphinxcontrib-applehelp 1.0.2

---

poetry.lock

Upgrade sphinxcontrib-devhelp from 1.0.1 to 1.0.2.

Upgrade to sphinxcontrib-devhelp 1.0.2

---

poetry.lock

Upgrade sphinxcontrib-qthelp from 1.0.2 to 1.0.3.

Upgrade to sphinxcontrib-qthelp 1.0.3

---

poetry.lock

Upgrade sphinxcontrib-serializinghtml from 1.1.3 to 1.1.4.

Upgrade to sphinxcontrib-serializinghtml 1.1.4

---

poetry.lock
pyproject.toml

Upgrade flake8-annotations from 2.0.0 to 2.0.1.

Upgrade to flake8-annotations 2.0.1

---

poetry.lock

Upgrade click from 7.0 to 7.1.1.

Upgrade to click 7.1.1

---

poetry.lock

Upgrade safety from 1.8.5 to 1.8.7.

Upgrade to safety 1.8.7

---

poetry.lock
pyproject.toml

Upgrade mypy from 0.761 to 0.770.

Upgrade to mypy 0.770

---

poetry.lock

Upgrade dparse from 0.4.1 to 0.5.0.

Upgrade to dparse 0.5.0

---

poetry.lock

Upgrade pytest from 5.3.5 to 5.4.1.

Upgrade to pytest 5.4.1

---

poetry.lock

Upgrade pyyaml from 5.3 to 5.3.1.

Upgrade to pyyaml 5.3.1

---

poetry.lock

Upgrade wcwidth from 0.1.8 to 0.1.9.

Upgrade to wcwidth 0.1.9

---

.gitattributes

https://prettier.io/docs/en/options.html#end-of-line
See also https://github.com/prettier/prettier/issues/8112

Enable end-of-line normalization with Git attributes

---

poetry.lock

Bump pyyaml from 5.3.1 to 5.4.1

Bump pyyaml from 5.3.1 to 5.4.1

---

poetry.lock

Bump jinja2 from 2.11.2 to 2.11.3

Bump jinja2 from 2.11.2 to 2.11.3

---

.pre-commit-config.yaml
noxfile.py
poetry.lock
pyproject.toml

- ➕ [poetry] Add pyupgrade ^2.29.0 to development dependencies
- 🔧 [nox] Install pyupgrade in pre-commit session
- 🔧 [pre-commit] Add pyupgrade hook

👷 [pre-commit] Add pre-commit hook for pyupgrade

---

noxfile.py

Closes https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/1102

Typeguard matching GA / nox sessions
